version: '3.8'

services:
  # The Core Backend & Embedded DB (PocketBase)
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: rom-dashboard-backend
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
    environment:
      - POCKETBASE_DATA_DIR=/pb_data

  # Next.js Web Interface & Real-time Build Tracker
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rom-dashboard-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_PB_URL=http://localhost:8090
      - POCKETBASE_INTERNAL_URL=http://pocketbase:8090
      - NEXT_PUBLIC_VAPID_PUBLIC_KEY=BPxSg3jF_STRDhIDP8Oz6Kz2KAWOGonH7grcQDUmnA6lT7rMOfCiYTpKm9SeQfXZKcqlXL5NvEojoxWnrAYj9cU
      - VAPID_PRIVATE_KEY=sUmWEs8T53JDpRU87Oq0SbS8r4NWRLYcvHrhtSRebg8
      - VAPID_SUBJECT=mailto:duoplesos@gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=duoplesos@gmail.com
      - SMTP_PASS=lqxznnhqdvumcopj
      - SMTP_FROM="DuoplesOS CI/CD <duoplesos@gmail.com>"
      - NOTIFICATION_EMAIL_TO=duoples77@gmail.com,duoplesos@gmail.com
      - BUILD_SERVER_HOST=192.168.2.192
    depends_on:
      - pocketbase
